name: Hello World Pipeline

on:
  push:
    branches: [ main ]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4

      - name: Step 2 - Print Hello
        run: echo "Hello"

      - name: Step 3 - Print World